# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'LBSAR' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LBSAR
  pod 'GoogleMaps', '6.0.0'
  pod 'GooglePlaces', '6.0.0'
  pod 'GooglePlacesAPI', '1.1.4'
  pod 'Polyline', '4.2.1'
  pod 'Cosmos', '21.0.0'
  pod 'SVProgressHUD', '2.2.5'
  pod 'HDAugmentedReality', '3.0.0'  end

  target 'LBSARTests' do
    inherit! :search_paths
end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        end
    end
end